In [1]:
import numpy as np

#Creating Array
my_list=[1,2,3,4,5,6]
print(my_list)
array=np.array(my_list, dtype=int)
print(array)

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


In [2]:
#Properties of array
print(type(array))
print(len(array))
print(array.ndim)
print(array.shape)

<class 'numpy.ndarray'>
6
1
(6,)


In [3]:
#Reshaping array
array2=array.reshape(3, 2)
print(array2)
array2.shape

array3=array.reshape(3,-1)
print(array3)
print(array3.ndim)

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
2


In [4]:
#Initializing numpy arrays from Python lists
my_list2=[1,2,3,4,5]
my_list3=[2,2,3,4,5]
my_list4=[3,2,3,4,5]
mul_arr=np.array([my_list2,my_list3,my_list4])
print(mul_arr)

mul_arr.reshape(1,15)

[[1 2 3 4 5]
 [2 2 3 4 5]
 [3 2 3 4 5]]


array([[1, 2, 3, 4, 5, 2, 2, 3, 4, 5, 3, 2, 3, 4, 5]])

In [5]:

#NumPy Attributes
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [6]:
#Reshaping the ndarray
a.shape=(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [7]:
#Reshape function to resize an array
b=a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [8]:
r=range(24)
print(r)

range(0, 24)


In [9]:
#Array of evenly spaced numbers
a=np.arange(24)
print(a)
print(a.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1


In [10]:
#Reshaping the array 'a'
b=a.reshape(6,4,1)
print(b)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]]

 [[16]
  [17]
  [18]
  [19]]

 [[20]
  [21]
  [22]
  [23]]]


In [11]:
#Length of each element in array
x=np.array([1,2,3,4,5], dtype=np.int8)
print(x.itemsize)
x=np.array([1,2,3,4,5], dtype=np.float32)
print(x.itemsize)

1
4


In [12]:
#Arithmetic Operations
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [13]:
#Addition
print(x+y)
print(np.add(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [14]:
#Subtraction
print(x-y)
print(np.subtract(x,y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [15]:
#Multiplication
print(x*y)
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [16]:
#Dot
print(x.dot(y))
print(np.dot(x,y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [17]:
#Divide
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [18]:
#Row, Column wise
print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

10
[4 6]
[3 7]
